runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /(example\.html)$
  static_files: static/\1
  upload: static/(.*)

- url: /
  script: main.app

# All other endpoints require admin log in.
# Cron requests have admin privileges.
- url: .*
  script: main.app
  login: admin
